use crate::{claude_web_sync, diagnostics, hook_watcher, pty_manager};

use jieba_rs::Jieba;
use notify::{Event, RecommendedWatcher, RecursiveMode, Watcher};
use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::mpsc::channel;
use std::sync::LazyLock;
use std::sync::Mutex;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tantivy::collector::TopDocs;
use tantivy::query::QueryParser;
use tantivy::schema::{self, Value as TantivyValue, *};
use tantivy::tokenizer::{LowerCaser, TextAnalyzer, Token, TokenStream, Tokenizer};
use tantivy::{doc, Index, IndexWriter, ReloadPolicy, Term};
use tauri::ipc::Channel;
use tauri::{Emitter, Manager};

mod core;
pub(crate) use core::*;
mod maas_types;
pub(crate) use maas_types::*;
mod session_listing;
pub(crate) use session_listing::*;
mod session_parsing;
pub(crate) use session_parsing::*;
mod session_bridge;
pub(crate) use session_bridge::*;
mod session_cache;
pub(crate) use session_cache::*;
mod session_messages;
pub(crate) use session_messages::*;
mod search;
pub(crate) use search::*;
mod commands;
pub(crate) use commands::*;
mod agents;
pub(crate) use agents::*;
mod skills;
pub(crate) use skills::*;
mod codex_commands;
pub(crate) use codex_commands::*;
mod knowledge_reference;
pub(crate) use knowledge_reference::*;
mod docs;
pub(crate) use docs::*;
mod marketplace_catalog;
pub(crate) use marketplace_catalog::*;
mod template_install;
pub(crate) use template_install::*;
mod context;
pub(crate) use context::*;
mod activity;
pub(crate) use activity::*;
mod annual_report;
pub(crate) use annual_report::*;
mod command_stats;
pub(crate) use command_stats::*;
mod settings_core;
pub(crate) use settings_core::*;
mod session_migration;
pub(crate) use session_migration::*;
mod settings_patch;
pub(crate) use settings_patch::*;
mod command_routers;
pub(crate) use command_routers::*;
mod command_registry;
pub(crate) use command_registry::*;
mod provider_context;
pub(crate) use provider_context::*;
mod maas_commands;
pub(crate) use maas_commands::*;
mod maas_model_fetch;
pub(crate) use maas_model_fetch::*;
mod extensions;
pub(crate) use extensions::*;
mod agent_runtime;
pub(crate) use agent_runtime::*;
mod agent_harness;
pub(crate) use agent_harness::*;
mod lovcode_version;
pub(crate) use lovcode_version::*;
mod pty;
pub(crate) use pty::*;
mod workspace;
pub(crate) use workspace::*;
mod hook_watcher_commands;
mod project_logo;
pub(crate) use project_logo::*;
mod lovstudio_auth;
pub(crate) use lovstudio_auth::*;
mod feedback_types;
pub(crate) use feedback_types::*;
mod feedback_github;
pub(crate) use feedback_github::*;
mod feedback_commands;
pub(crate) use feedback_commands::*;
mod filesystem;
pub(crate) use filesystem::*;
mod diagnostics_commands;
mod git;
mod macos_window;
pub(crate) use macos_window::*;
mod claude_web;
pub(crate) use claude_web::*;
mod network;
pub(crate) use network::*;
mod run;
pub use run::run;
