use jieba_rs::Jieba;
use notify::{Event, RecommendedWatcher, RecursiveMode, Watcher};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::mpsc::channel;
use std::sync::LazyLock;
use std::sync::Mutex;
use std::time::{Duration, SystemTime, UNIX_EPOCH};
use tantivy::collector::TopDocs;
use tantivy::query::QueryParser;
use tantivy::schema::{self, Value as TantivyValue, *};
use tantivy::tokenizer::{LowerCaser, TextAnalyzer, Token, TokenStream, Tokenizer};
use tantivy::{doc, Index, IndexWriter, ReloadPolicy, Term};
use tauri::ipc::Channel;
use tauri::{Emitter, Manager};

mod core;
pub(crate) use core::*;
mod cli;
pub(crate) use cli::*;
mod session_listing;
pub(crate) use session_listing::*;
mod session_parsing;
pub(crate) use session_parsing::*;
mod session_cache;
pub(crate) use session_cache::*;
mod session_messages;
pub(crate) use session_messages::*;
mod search;
pub(crate) use search::*;
mod ataru;
mod settings_core;
pub(crate) use settings_core::*;
mod command_registry;
pub(crate) use command_registry::*;
mod macos_window;
pub(crate) use macos_window::*;
mod run;
pub use run::run;
